# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x12nexl.opportunities\"\xc4\x01\n\x17OpportunityNotification\x12\x16\n\x0eopportunity_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x31\n\x04type\x18\x03 \x01(\x0e\x32#.nexl.opportunities.OpportunityType\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x13\n\x0b\x63lient_name\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\t\"Q\n\x0f\x41nalysisRequest\x12\x18\n\x10\x63ommunication_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x13\n\x0b\x63lient_name\x18\x03 \x01(\t\"\x95\x01\n\x10\x41nalysisResponse\x12\x18\n\x10\x63ommunication_id\x18\x01 \x01(\t\x12?\n\ropportunities\x18\x02 \x03(\x0b\x32(.nexl.opportunities.ExtractedOpportunity\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x15\n\rerror_message\x18\x04 \x01(\t\"\xb2\x01\n\x14\x45xtractedOpportunity\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x31\n\x04type\x18\x03 \x01(\x0e\x32#.nexl.opportunities.OpportunityType\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x16\n\x0e\x65xtracted_text\x18\x05 \x01(\t\x12\x17\n\x0f\x65stimated_value\x18\x06 \x01(\t*\x8c\x01\n\x0fOpportunityType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0bREAL_ESTATE\x10\x01\x12\x12\n\x0e\x45MPLOYMENT_LAW\x10\x02\x12\x1c\n\x18MERGERS_AND_ACQUISITIONS\x10\x03\x12\x19\n\x15INTELLECTUAL_PROPERTY\x10\x04\x12\x0e\n\nLITIGATION\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPPORTUNITYTYPE']._serialized_start=654
  _globals['_OPPORTUNITYTYPE']._serialized_end=794
  _globals['_OPPORTUNITYNOTIFICATION']._serialized_start=39
  _globals['_OPPORTUNITYNOTIFICATION']._serialized_end=235
  _globals['_ANALYSISREQUEST']._serialized_start=237
  _globals['_ANALYSISREQUEST']._serialized_end=318
  _globals['_ANALYSISRESPONSE']._serialized_start=321
  _globals['_ANALYSISRESPONSE']._serialized_end=470
  _globals['_EXTRACTEDOPPORTUNITY']._serialized_start=473
  _globals['_EXTRACTEDOPPORTUNITY']._serialized_end=651
# @@protoc_insertion_point(module_scope)
