"""Initial schema

Revision ID: 9dd6863490de
Revises: 
Create Date: 2025-11-04 11:02:48.996481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd6863490de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.Enum('EMAIL', 'MEETING', 'NOTE', name='communicationtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_communications_client_name', 'communications', ['client_name'], unique=False)
    op.create_index('idx_communications_created_at', 'communications', ['created_at'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('communication_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('opportunity_type', sa.Enum('REAL_ESTATE', 'EMPLOYMENT_LAW', 'MERGERS_AND_ACQUISITIONS', 'INTELLECTUAL_PROPERTY', 'LITIGATION', name='opportunitytype'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estimated_value', sa.String(length=50), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'REVIEWING', 'CONTACTED', 'CLOSED', 'ARCHIVED', name='opportunitystatus'), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_opportunities_communication_id', 'opportunities', ['communication_id'], unique=False)
    op.create_index('idx_opportunities_confidence', 'opportunities', ['confidence'], unique=False)
    op.create_index('idx_opportunities_detected_at', 'opportunities', ['detected_at'], unique=False)
    op.create_index('idx_opportunities_type', 'opportunities', ['opportunity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_opportunities_type', table_name='opportunities')
    op.drop_index('idx_opportunities_detected_at', table_name='opportunities')
    op.drop_index('idx_opportunities_confidence', table_name='opportunities')
    op.drop_index('idx_opportunities_communication_id', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index('idx_communications_created_at', table_name='communications')
    op.drop_index('idx_communications_client_name', table_name='communications')
    op.drop_table('communications')
    # ### end Alembic commands ###
